language: go
sudo: false
before_script:
  - go vet ./...
  - go get github.com/mattn/goveralls
  - go test -v -covermode=count -coverprofile=coverage.out
  - $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN
install:
  # Add Godeps dependencies to GOPATH and PATH
  #- export GOPATH="${TRAVIS_BUILD_DIR}/Godeps/_workspace:$GOPATH"
  #- export PATH="${TRAVIS_BUILD_DIR}/Godeps/_workspace/bin:$PATH"
